# Generated by Django 5.0.1 on 2026-02-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaanamnese',
            name='frequencia_esporte',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quantas Vezes por Semana'),
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='nivel_atividade_fisica',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentário'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], max_length=20, verbose_name='Nível de Atividade Física'),
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='qual_esporte',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qual Esporte Pratica'),
        ),
    ]
